### ISSUE TITLE
terminate called after throwing an instance of 'oneflow::RuntimeException'

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/one-yolov5#106]
## 问题描述
启动指令:  `python train.py --data coco128.yaml --weights '' --cfg yolov5s.yaml --img 640`

2023.01.12号编译的oneflow版本可以正常执行上面 这条启动指令，
使用 2023.01.18号编译的oneflow 版本，发生报错，报错信息如下：
## 报错信息
terminate called after throwing an instance of 'oneflow::RuntimeException'
![报错](https://foruda.gitee.com/images/1674093923818833887/f78e4921_10213136.png "屏幕截图")

注意:
- 2023.01.18号编译的oneflow 
-  可复现代码  `git clone  git@github.com:Oneflow-Inc/one-yolov5.git  && git checkout debug_RuntimeException` 
-  复现启动指令:  `python train.py --data coco128.yaml --weights '' --cfg yolov5s.yaml --img 640`

## 使用环境信息
- 机器 oneflow27-root( GPU 8 NVIDIA GeForce RTX 3090, 24268MiB)
- python: 3.8
- 2023.01.18号编译的oneflow

**Comment by ccssu** [comment]
## 前言
-  使用代码  `git clone  git@github.com:Oneflow-Inc/one-yolov5.git  && git checkout debug_RuntimeException` 
-  启动指令:  `python train.py --data coco128.yaml --weights '' --cfg yolov5s.yaml --img 640`
- 机器 oneflow27-root( GPU 8 NVIDIA GeForce RTX 3090, 24268MiB)
- python: 3.8
- 编译的oneflow 

## 第一次出现问题的 commit

第一次出现问题的 commit: `1761f66b29736c45389ead19a0981c9bf4224346`
'Author', ' Luyang <flowingsun007@163.com>']|k='Date' v=['Date', '   Mon Jan 16 09 : 33: 41 2023 +0800
![image](https://user-images.githubusercontent.com/109639975/213613543-af4cf1d9-6830-4a71-a06b-2697ff23f088.png)
**图1.0 画框处为第一次出现问题的commit信息。**

## 测试
下图 确认 k='commit' v='1761f66b29736c45389ead19a0981c9bf4224346'  测试出现错误。
![image](https://user-images.githubusercontent.com/109639975/213613347-e5d05027-21c5-451a-8439-5f712e2e281b.png)
图2.0 画框处对应 测试的 commit 信息

下图 确认 k='commit' v='20340e43c26fff64920f386a75708a9f89d90ace' 测试结果正常。
![image](https://user-images.githubusercontent.com/109639975/213614634-54d4f182-d840-442a-a4eb-4e49a56072f2.png)

图3.0 画框处对应 测试的 commit 信息
## 附件
<details close>
<summary> 二分找bug脚本 </summary>

```python
import os

make_oneflow = "sh /home/fengwen/make_flow_reserd.sh "
cmd = "sh /home/fengwen/one-yolov5/runs/run.sh"
path_git_log_file = "/home/fengwen/oneflow_git.log"
rm_oneflow_build = "cd /data/dataset/fengwen/package/oneflow \
                    &&  rm build -rf  \
                    "
DATAS = []


def check(mid):
    os.system(make_oneflow + DATAS[mid].commit)

    with open('/home/fengwen/one-yolov5/runs/debug.log', mode='a+') as fp:
        fp.write("|" + str(DATAS[mid]) + "|")
    result = os.system(cmd) 
    with open('/home/fengwen/one-yolov5/runs/debug.log', mode='a+') as fp:
        fp.write(f'{result=}|\n')
    return result != 0 

class Data:
    def __str__(self) -> str:
        result = []
        for k, v in self.__dict__.items():
            if k is None or v is None:
                continue
            result.append(f"{k=} {v=}")
        return "|".join(result)


def load_git_log(
    file,
    start_commit="5f95f0014830554f0809bb30be576c9121c6cf04", # False 01-16
    end_commit="29b1b4ea27095c55e1e91577652fb6d4db09e5ee", # True 01-12
):
    with open(file=file, mode="r") as fp:
        rows = [x.strip() for x in fp]
        data = Data()
        for row in rows:
            if start_commit is not None:
                if start_commit in row:  # 确认 False
                    x = row.split(" ")
                    setattr(data, x[0], x[1])
                    start_commit = None
            else:
                if "Author" in row or "Date" in row:
                    x = row.split(":")
                    setattr(data, x[0], row)
                elif "commit" in row:
                    DATAS.append(data)
                    data = Data()
                    x = row.split(" ")
                    setattr(data, x[0], row)

            if end_commit in row:
                break

def test():
    # os.system(make_oneflow + '29b1b4ea27095c55e1e91577652fb6d4db09e5ee')
    result = (os.system(cmd) == 0)
    print(result)

def main():
    load_git_log(path_git_log_file)
    # 0 False end True
    left, right = 0, len(DATAS) - 1
    
    for index,row in enumerate(DATAS):
        print(index,str(row))

    while left <= right:
        mid = (left + right) // 2
        if check(mid):
            left = mid + 1
        else:
            right = mid - 1


if __name__ == "__main__":
    main()

```
</details>

**Comment by BBuf** [comment]
> 
这个脚本看起来不错，可以分享到oneteam里。

@ccssu

**Comment by daquexian** [comment]
> > 
> 
> 这个查找bug的脚本看起来不错，可以分享到oneteam里。
> 
> @ccssu

诶，可以考虑使用 git 自带的 git bisect run 命令加一个返回 0 表示成功返回非 0 表示失败的任意命令/脚本 https://github.com/Oneflow-Inc/OneTeam/issues/911
