### ISSUE TITLE
模型导出 ：export failure 10.7s: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/one-yolov5#112]
### <a id="preface">问题描述</a>

在one-yolov5同步上游分支[upgrade_yolov5_064365d8683fd002e9ad789c1e91fa3d021b44f0](https://github.com/Oneflow-Inc/one-yolov5/tree/upgrade_yolov5_064365d8683fd002e9ad789c1e91fa3d021b44f0)代码中中训练的模型导出报错 ：export failure 10.7s: cannot unpack non-iterable NoneType object

|one-yolov5仓库|训练的模型是否正常导出|
|---|---|
|main分支[代码](https://github.com/Oneflow-Inc/one-yolov5/tree/main) | 是|
| 同步的上游分支[upgrade_yolov5_064365d8683fd002e9ad789c1e91fa3d021b44f0](https://github.com/Oneflow-Inc/one-yolov5/tree/upgrade_yolov5_064365d8683fd002e9ad789c1e91fa3d021b44f0)| 否| 

同步的上游分支[upgrade_yolov5_064365d8683fd002e9ad789c1e91fa3d021b44f0](https://github.com/Oneflow-Inc/one-yolov5/tree/upgrade_yolov5_064365d8683fd002e9ad789c1e91fa3d021b44f0) 报错日志如下。
 

###    <a id="error_log"> 报错日志 </a>

one-yolov5同步最新代码分支:
全部报错信息:
```shell
[34m[1mexport: [0mdata=data/coco128.yaml, weights=['/home/fengwen/one-yolov5/runs/train/exp/weights/last.of'], imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['onnx']
YOLOv5 ðŸš€ v1.2.0-23-g746a0b89 Python-3.8.13 oneflow-0.9.1+cu117.git.f9dbf07b6e CPU

Fusing layers... 
Model summary: 157 layers, 1867405 parameters, 115005 gradients

[34m[1mOneFlow:[0m starting from /home/fengwen/one-yolov5/runs/train/exp/weights/last.of with output shape (1, 25200, 85) (18.2 MB)

[34m[1mONNX:[0m starting export with onnx 1.12.0...
type(temp)=<class 'models.yolo.DetectionModel'>
Converting model to onnx....
Succeed converting model, save model to /home/fengwen/one-yolov5/runs/train/exp/weights/last.onnx
Comparing result between oneflow and onnx....
a[1040318]=-0.04244624450802803, b[1040318]=120.0
a[1067518]=4.847601890563965, b[1067518]=120.0
a[1074318]=-1.122959017753601, b[1074318]=119.99993896484375
。。。
a[2126618]=1.2650983333587646, b[2126618]=120.0
a[2126702]=0.47027212381362915, b[2126702]=64.0
[34m[1mONNX:[0m export failure: 
[34m[1mONNX:[0m export failure â�Œ 10.7s: cannot unpack non-iterable NoneType object
a[2126703]=1.246699571609497, b[2126703]=120.0
a[2126787]=-2.708296537399292, b[2126787]=64.0
a[2126788]=-1.9929529428482056, b[2126788]=120.0
a[2126872]=2.1239521503448486, b[2126872]=64.0
a[2126873]=-1.6809101104736328, b[2126873]=120.0
a[2126957]=-1.4159680604934692, b[2126957]=64.0
a[2126958]=0.2895963788032532, b[2126958]=120.0

````

one-yolov5 main分支:
![image](https://user-images.githubusercontent.com/109639975/219253779-2d5300bc-9269-4ec2-b43e-2413513b2050.png)

## <a id="Environmental_info"> 环境信息</a>
- 机器: oneflow27-root
- 2023-02-16编译的 oneflow.__version__= 0.9.1+cu117.git.f9dbf07b6e
- oneflow-onnx版本:  oneflow_onnx.__version__ = 0.1.1

**Comment by ccssu** [comment]
上面报错出现在 ` assert np.allclose(a, b, rtol=rtol, atol=atol) ` 这一行的断言，如下图所示:

![image](https://user-images.githubusercontent.com/109639975/219366734-69e65978-3b67-40fe-ad30-01c32aebad6c.png)

**Comment by ccssu** [comment]
## 尝试解决上面问题个人的思路
使用工具 `pdb`
- [x] 检查模型的输入和输出是否正确，并验证在OneFlow和ONNX之间传递的数据是否相同。
- [x] 尝试在GPU上运行模型，检查结果是否一致。如果结果一致，则可能是CPU计算的精度误差导致结果不同。

**Comment by BBuf** [comment]
这个是导出哪个检测模型？

**Comment by ccssu** [comment]
> 

yolov5s，流程：跑一个epochs后得到的模型权重，然后再测试导出
