### ISSUE TITLE
one-yolov5 sync-bn 断点续训精度下降

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/one-yolov5#26]
目前处于猜测阶段，目前有如下两个依据：
## 1. 在这个issues: https://github.com/Oneflow-Inc/one-yolov5/issues/21   
采用syncbn训练，中途有中断继续恢复训练，可以看到在第194个，250个epoch处附近出现明显下降(详细数据可见https://github.com/Oneflow-Inc/one-yolov5/issues/21#issue-1367167785 ）
![imgs](https://user-images.githubusercontent.com/109639975/189792135-565c237d-637a-48af-a173-703f6ac582d8.png)
## 2.  在isses的map结果: https://github.com/Oneflow-Inc/one-yolov5/issues/19
由于服务器重启，下图中在第90个epoch附近有明显下降。
![imgs](https://user-images.githubusercontent.com/109639975/189090504-0c767f24-7601-4f51-9e3b-91ff81e2e7be.png)

结合最新的不采用sync 加载torch初始化 训练结果
在第 24个epoch 
  ||是否加载torch初始化| metrics/mAP_0.5| metrics/mAP_0.5:0.95|
  | --- | ---  | --- | --- |
  | yolov5n|是 |    0.2547,    |        0.14129,  |
  | yolov5n|否|     0.25279,   |          0.14134, |

可以看下图两个圈所标注，他们都精度值几乎一致。所以猜测应该是精度值受到 训练中断然后恢复训练的影响。
![image](https://user-images.githubusercontent.com/109639975/189804006-1a6a392e-46cd-4df9-a1d8-b0c9ffee567d.png)

**Comment by ccssu** [comment]
最新的不采用sync 训练结果
在第 103个epoch 
  | |是否中断| metrics/mAP_0.5| metrics/mAP_0.5:0.95|
  | --- | ---  | --- | --- |
  | yolov5n|是 | 0.35528       |    0.2045      |
  | yolov5n|否|     0.36439   |    0.2123      |

可以看出在不中断map值高了将近一个百分点，并且没有明显的下降趋势，如下图(根据最新的results.txt 画的map趋势图)所示:
![image](https://user-images.githubusercontent.com/109639975/189940643-5c211a51-8e1f-4694-ab1b-cc35162fad3f.png)

预计完成300个epoch训练在2022-09-13：19:00左右

**Comment by ccssu** [comment]
在最新的不采用syncbn且不中断训练得到的精度相比目标差了1~2个点。具体数据如上面的[comment：](https://github.com/Oneflow-Inc/one-yolov5/issues/26#issuecomment-1245578282)

现在同步了一下原来从one-yolov5拉取的torch版本，进行不采用syncbn且不中断训练实验，主要在train.py进行两处修改
(1) 把shuffle = False 改为 shuffle = True，表示在进行训练周期后要对数据进行打乱，目的降低模型拟合性
(2) init_seed函数从 init_seed(1，True)修改为 init_seed( opt.seed + RANK + 1，True)   。 (原来做loss 对齐 train.py中 init_seed函数传入固定为 1 。原因：oneflow会修改默认的 RANK ，可见 https://github.com/Oneflow-Inc/OneTeam/issues/1602#issuecomment-1211821128 。)

下面是这次训练的结果，更新中。。。
![image](https://user-images.githubusercontent.com/109639975/190445349-7e017a2b-4e8e-4a1d-95b4-326e5187c3c1.png)

目前opochs:  93
 | |metrics/mAP_0.5|metrics/mAP_0.5:0.95|
 | --- | --- | --- |
 |当前训练值| 36.015 | 20.868 |
|上次训练值| 35.821 | 20.813 |
|当前训练值-上次训练值|  0.194 | 0.055 |
| 目标值 |  45.6 | 27.7 | 
|当前训练值 - 目标值|-9.585 | -6.832|

**Comment by ccssu** [comment]
上面实验( https://github.com/Oneflow-Inc/one-yolov5/issues/26#issuecomment-1248267943 )的精度无法达标的根据这个pr https://github.com/Oneflow-Inc/oneflow/pull/9102 修改oneflow源码，

不采用syncbn且不中断训练
机器： oneflow27-root
指令： python -m oneflow.distributed.launch --nproc_per_node 2 train.py --data data/coco.yaml --weights ' ' --cfg models/yolov5n.yaml
下面是这次训练的结果
![image](https://user-images.githubusercontent.com/109639975/190932378-d96f2a4d-81f9-4c1f-b102-d7943ba52f23.png)

目前opochs:  273
 | |metrics/mAP_0.5|metrics/mAP_0.5:0.95|
 | --- | --- | --- |
 |当前训练值| 42.506 | 25.464 |
|上次训练值| 42.300 | 25.294 |
|当前训练值-上次训练值|  0.206 | 0.170 |
| 目标值 |  45.6 | 27.7 | 
|当前训练值 - 目标值|-3.094 | -2.236|

**Comment by ccssu** [comment]
## 环境

机器：oneflow27-root
配置项:
- shuffle  = True
-  sync-bn = True 
-  通过加载torch初始化权重训练
-  --workers 8
##  数据 

目前opochs:  21 （数据继续更新中。。。）
 | |metrics/mAP_0.5|metrics/mAP_0.5:0.95|
 | --- | --- | --- |
 |当前训练值| 23.631 | 13.010 |
| 目标值 |  45.6 | 27.7 | 
|当前训练值 - 目标值|-21.969 | -14.690|

**Comment by yuanms2** [comment]
Yolo 受不受swin 那边发现的初始化的影响

**Comment by ccssu** [comment]
> Yolo 受不受swin 那边发现的初始化的影响

目前Yolo还没有训到目标精度，我无法确定，等会我去问问。

**Comment by BBuf** [comment]
> Yolo 受不受swin 那边发现的初始化的影响

那个改动已经在我们的训练分支了

**Comment by yuanms2** [comment]
yolo 的精度还是没有对齐么
