### ISSUE TITLE
使用sync-bn后速度下降快

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/one-yolov5#65]
## 问题：
在one-yolov5项目中使用sync-bn速度明显下降。
## 数据表
下面表格的数据都是在a100训练1个epoch的结果，通过和pytorch耗时对比，使用sync-bn，以OneFlow为后端相比于PyTorch为后端的yolov5，耗时增加的更明显。

| 后端    | batch | sync-bn | gpu数 | time(min) |
| ------- | ----- | ------- | ----- | --------- |
| OneFlow | 128   | False   | 8     | 7.5       |
| OneFlow | 128   | True    | 8     | 11.34     |
| PyTorch | 128   | False   | 8     | 6.96      |
| PyTorch | 128   | True    | 8     | 7.20      |

复现指令：
- `OneFlow` 版本yolov5
```shell
python  -m oneflow.distributed.launch --nproc_per_node 8 train.py --batch 128 --cfg  models/hub/yolov5s6.yaml  --weights '' --data data/coco.yaml --img 1280 --epochs 1  --hyp  data/hyps/hyp.scratch-high.yaml --sync-bn
```
- `PyTorch` 版yolov5
```shell
python -m torch.distributed.run --nproc_per_node  8 train.py --batch 128 --cfg  models/hub/yolov5s6.yaml  --weights '' --data data/coco.yaml --img 1280 --epochs 1  --hyp  data/hyps/hyp.scratch-high.yaml  --sync-bn
```
## 系统信息
机器
> a100

oneflow.__version__
>'0.8.1+cu118.git.b21eee7d28'

torch.__version__
>'1.14.0.dev20221022+cu116'

**Comment by Ldpe2G** [comment]
| 后端    | batch | sync-bn | gpu数 | time     | 每张卡平均显存占用 |
| ------- | ----- | ------- | ----- | -------- | ------------------ |
| OneFlow | 128   | False   | 8     | 6min35s  | ~32.8G             |
| OneFlow | 128   | True    | 8     | 10min10s | ~32.8G             |
| PyTorch | 128   | False   | 8     | 5min59s  | ~26.5G             |
| PyTorch | 128   | True    | 8     | 6min27s  | ~26.5G             |

oneflow版本：'0.8.1+cu118.git.e1d5b63e43'

我在A100重新测了下，结论是差不多的，不过还发现 oneflow 的显存占用比 torch 要多6G左右。

**Comment by Ldpe2G** [comment]
同时注释掉 oneflow 和 torch 的 sync-bn 中，前向包含的 `all_gather` 和 后向包含的 ` all_reduce`操作。

再测 1 个epoch的耗时如下：

oneflow ： ~7min35s  
torch：      ~6min8s

对比上面的[实验结果](https://github.com/Oneflow-Inc/one-yolov5/issues/65#issuecomment-1309689749) 可知， 在 sync-bn 中前后向中增加通信操作，会使得 oneflow 耗时增加 ~2min35s，而 torch 只增加 19 s

**Comment by Ldpe2G** [comment]
通过单独查看前后向的 nsys，可以发现是前向的 `allgather` 操作， oneflow 的实现效率非常低，待优化。

后向 oneflow 和 torch 耗时是差不多的

**Comment by Ldpe2G** [comment]
| 后端    | batch | sync-bn | gpu数 | time     | 每张卡平均显存占用 |
| ------- | ----- | ------- | ----- | -------- | ------------------ |
| OneFlow | 128   | False   | 8     | 12min11s  | ~33G             |
| OneFlow master | 128   | True    | 8     | 21min34s | ~33G             |
| OneFlow https://github.com/Oneflow-Inc/oneflow/pull/9624 | 128   | True    | 8     | 13min0s | ~33G             |


可以看到在用了新的 all_gather 实现之后， 使用 sync-bn 速度 相比之前下降少很多了

**Comment by ccssu** [comment]
> oneflow版本: babaa7e287 (HEAD -> dev_refine_syncbn_allgather,


|     | 后端    | batch | sync_bn | multi_tensor_optimize | gpu数 | time(min) |
| --- | ------- | ----- | ------- | --------------------- | ----- | --------- |
| (1) | OneFlow | 128   | True    | True                  | 8     | 9.78      |
| (2) | OneFlow | 128   | True    | False                 | 8     | 11.52     |
| (3) | OneFlow | 128   | False   | False                 | 8     | 15.66     |
| (4) | OneFlow | 128   | False   | True                  | 8     | 16.20     |


实验数据记录的是均是1个epoch的时间，示例如下图。
![image](https://user-images.githubusercontent.com/109639975/208418851-23f997f5-d203-49ee-84df-431752c8ed7d.png)


<details close>
<summary> 复现指令 </summary>

```shell
cd ~/one-yolo/

sync_bn=(' ' '--sync-bn')
mto=(' ' '--multi_tensor_optimize')

mkdir -p logs 
for((i=0;i<${#sync_bn[*]};i++))
do
    for((j=0;j<${#mto[*]};j++))
    do 
        DATESTR=$(date +"%m-%d-%H-%M")
        run_cmd="python  -m oneflow.distributed.launch \
            --nproc_per_node 8 train.py \
            --batch 128 \
            --cfg  models/hub/yolov5s6.yaml \
            --weights '' \
            --data data/coco.yaml \
            --img 1280 \
            --epochs 1  \
            --hyp  data/hyps/hyp.scratch-high.yaml \
            ${sync_bn[i]} \
            ${mto[j]}\
            2>&1 | tee logs/log-${DATESTR}.txt"
        echo ${run_cmd}
        eval ${run_cmd}
    done
done
set +x
```

</details>

## 环境信息
- 机器 ： a100
- oneflow版本: babaa7e287 (HEAD -> dev_refine_syncbn_allgather,
- one-yolov5 maseter分支
