### ISSUE TITLE
显存问题跟踪

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/one-yolov5#71]
### 显存比较

NVIDIA GeForce RTX 3080 Ti, 12054MiB

#### yolov5s 显存占用测试
- `python train.py --batch 16 --cfg models/yolov5s.yaml --weights '' --data coco.yaml --img 640 --device 1 --epoch 300`

|网络|框架|显存占用|
|--|--|--|
|yolov5s|oneflow|8509MiB|
|yolov5s|pytorch|8091MiB|

只保留backbone部分，loss直接用.sum()代替之后的显存占用情况：

|网络|框架|显存占用|
|--|--|--|
|yolov5s backbone|oneflow|9089MiB|
|yolov5s backbone|pytorch|8467MiB|

从这组实验基本可以确定，就是纯网络部分占用的显存OneFlow会比PyTorch大。

#### yolov5s6 显存占用测试

- `python train.py --batch 4 --cfg models/hub/yolov5s6.yaml --weights '' --data coco.yaml --img 640 --device 1 --epoch 300`

|网络|框架|显存占用|
|--|--|--|
|yolov5s6|oneflow|8387MiB|
|yolov5s6|pytorch|8099MiB|

对应参数量更大的yolov5s6来说，即使在batch-size=4时，oneflow比pytorch增长的显存已经是200-300MiB了。德澎的测试结果显示在batch-size等于128时，oneflow的显存多了2-3G看起来是差不多的。

#### 独立复现方式

- `python3 models/yolo.py --cfg models/yolov5s.yaml --batch-size 16 --device 0`

并且在 yolo.py 中做如下修改：

```python
# Create model
    im.requires_grad_()
    for i in range(10000):
        y = model(im)
        loss = 0.0
        for j in range(len(y)):
            loss += y[j].sum()
        loss.backward()
        loss_np = loss.item()
```

|网络|框架|显存占用|
|--|--|--|
|yolov5s|oneflow|8417MiB|
|yolov5s|pytorch|8001MiB|

只运行网络部分，OneFlow相比PyTorch会多占用400+MiB显存。

接下来为了是否是反向过程中引入了多余的显存占用，我做了如下修改，即只运行模型前向：

```python
with torch.no_grad():
        for i in range(10000):
            y = model(im)
            for j in range(len(y)):
                y_j_item = y[j].sum().item()
```

|网络|框架|显存占用|
|--|--|--|
|yolov5s|oneflow|2629MiB|
|yolov5s|pytorch|2941MiB|

在前向过程中，OneFlow相比PyTorch反而会少占用312MiB显存。

所以问题肯定出在反向的时候某个部分相比PyTorch占用了过多显存。

先将 yolo.py 中的代码改成正常的bakcward，然后注释掉 yolov5s.yaml 中的 head，记录显存占用：

|网络|框架|显存占用|
|--|--|--|
|yolov5s|oneflow|6375MiB|
|yolov5s|pytorch|6483MiB|

可以看到完全去掉 head 部分之后 OneFlow 相比 PyTorch 还是有一点显存优势的，所以问题一定出在 head 部分。

我们把 head 的第一部分加上来，测试显存占用：

|网络|框架|显存占用|
|--|--|--|
|yolov5s|oneflow|6913MiB|
|yolov5s|pytorch|6863MiB|

可以看到加入head的第一部分，OneFlow显存上涨了6913-6375=538MiB，而PyTorch上涨了6863-6483=380MiB。所以一定是head里面第一个部分里面某个类型的op会加重显存增长。

观察 head 的第一部分构成：

```shell
 [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13
```

猜测只有 upsample 算子可能增长显存，通过对反向的分析发现OneFlow的UpsampleNearest2dGrad算子相比于PyTorch多存了一份x，而实际上在指定了scale_factor时我们不需要保存x即可以从dy和attr推导出dx的形状，并且cuda kernel也不需要依赖x，所以简单修改了这个UpsampleNearest2dGrad算子去掉了多保存的activation。在只开启head的第一部分时测试显存占用：

|网络|框架|显存占用|
|--|--|--|
|yolov5s|oneflow(优化前)|6913MiB|
|yolov5s|oneflow(优化后)|6875MiB|
|yolov5s|pytorch|6863MiB|

可以看到此优化是有用的，虽然由于activation比较少节省的显存有限只有38MiB，但是是一个隐藏的优化点。

接下来我们在yolov5.yaml里面只注释head部分最后一个Detect层，看一下显存占用：

|网络|框架|显存占用|
|--|--|--|
|yolov5s|oneflow|8147MiB|
|yolov5s|pytorch|8027MiB|

可以看到都不启用Detect层时，OneFlow相比于PyTorch的显存只会多100MiB左右，如果启用Detect层则会增加400+MiB，因此显存增长的大头都在Detect层。

比较奇怪的在于，把Detect层单独拿出来，设定和网络里面一样的输入Tensor和参数，并进行反向传播，OneFlow相比于PyTorch并不会有显存增加的情况。

```python
import oneflow as flow
import oneflow.nn as nn

class Detect(nn.Module):
    stride = None  # strides computed during build
    onnx_dynamic = False  # ONNX export parameter
    export = False  # export mode

    def __init__(self, nc=80, anchors=(), ch=(), inplace=True):  # detection layer
        super().__init__()
        self.nc = nc  # number of classes
        self.no = nc + 5  # number of outputs per anchor
        self.nl = len(anchors)  # number of detection layers
        self.na = len(anchors[0]) // 2  # number of anchors
        self.grid = [flow.empty(1)] * self.nl  # init grid
        self.anchor_grid = [flow.empty(1)] * self.nl  # init anchor grid
        self.register_buffer("anchors", flow.tensor(anchors).float().view(self.nl, -1, 2))  # shape(nl,na,2)
        self.m = nn.ModuleList(nn.Conv2d(x, self.no * self.na, 1) for x in ch)  # output conv

    def forward(self, x):
        for i in range(self.nl):
            y = self.m[i](x[i])  # conv
            bs, _, ny, nx = y.shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            y = y.view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2)
        return y 



detect = Detect(nc=80, anchors=[[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], ch=[128, 256, 512])
detect.to("cuda")

x0 = flow.randn(1, 128, 32, 32).to("cuda").requires_grad_()
x1 = flow.randn(1, 256, 16, 16).to("cuda").requires_grad_()
x2 = flow.randn(1, 512, 8, 8).to("cuda").requires_grad_()
x = [x0, x1, x2]

for i in range(100000):
    y = detect(x)
    loss = 0.0
    for j in range(len(y)):
        loss += y[j].sum()
    loss.backward()
    loss_np = loss.item()

```

**Comment by BBuf** [comment]
哦，我好像改错op了，应该是改upsample_neasest_1d而不是2d，等我有空改了再测试一下。

**Comment by wyg1997** [comment]
上面的例子有些 bug，修改后显存对于是这样：

```python
# 1360
#  import oneflow as flow
#  import oneflow.nn as nn
# 1090
import torch as flow
import torch.nn as nn


class Detect(nn.Module):
    stride = None  # strides computed during build
    onnx_dynamic = False  # ONNX export parameter
    export = False  # export mode

    def __init__(self, nc=80, anchors=(), ch=(), inplace=True):  # detection layer
        super().__init__()
        self.nc = nc  # number of classes
        self.no = nc + 5  # number of outputs per anchor
        self.nl = len(anchors)  # number of detection layers
        self.na = len(anchors[0]) // 2  # number of anchors
        self.grid = [flow.empty(1)] * self.nl  # init grid
        self.anchor_grid = [flow.empty(1)] * self.nl  # init anchor grid
        self.register_buffer("anchors", flow.tensor(anchors).float().view(self.nl, -1, 2))  # shape(nl,na,2)
        self.m = nn.ModuleList(nn.Conv2d(x, self.no * self.na, 1) for x in ch)  # output conv

    def forward(self, x):
        feat = []
        for i in range(self.nl):
            y = self.m[i](x[i])  # conv
            bs, _, ny, nx = y.shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            y = y.view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2)
            feat.append(y)  # 之前这里只返回了一个 Tensor，其他 Tensor 可能直接释放了
        return feat 



detect = Detect(nc=80, anchors=[[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], ch=[128, 256, 512])
detect.to("cuda")

x0 = flow.randn(16, 128, 32, 32).to("cuda").requires_grad_()
x1 = flow.randn(16, 256, 16, 16).to("cuda").requires_grad_()
x2 = flow.randn(16, 512, 8, 8).to("cuda").requires_grad_()
x = [x0, x1, x2]

for i in range(10000):
    y = detect(x)
    loss = 0.0
    for j in range(len(y)):
        loss += y[j].sum()
    loss.backward()
    loss_np = loss.item()
```

显存占用为 OneFlow: 1360、PyTorch: 1090，batchsize 为 16 的时候差了 270MB 了，可以从这个例子入手去定位。

**Comment by BBuf** [comment]
> 上面的例子有些 bug，修改后显存占用是这样：
> 
> ```python
> # 1360
> #  import oneflow as flow
> #  import oneflow.nn as nn
> # 1090
> import torch as flow
> import torch.nn as nn
> 
> 
> class Detect(nn.Module):
>     stride = None  # strides computed during build
>     onnx_dynamic = False  # ONNX export parameter
>     export = False  # export mode
> 
>     def __init__(self, nc=80, anchors=(), ch=(), inplace=True):  # detection layer
>         super().__init__()
>         self.nc = nc  # number of classes
>         self.no = nc + 5  # number of outputs per anchor
>         self.nl = len(anchors)  # number of detection layers
>         self.na = len(anchors[0]) // 2  # number of anchors
>         self.grid = [flow.empty(1)] * self.nl  # init grid
>         self.anchor_grid = [flow.empty(1)] * self.nl  # init anchor grid
>         self.register_buffer("anchors", flow.tensor(anchors).float().view(self.nl, -1, 2))  # shape(nl,na,2)
>         self.m = nn.ModuleList(nn.Conv2d(x, self.no * self.na, 1) for x in ch)  # output conv
> 
>     def forward(self, x):
>         feat = []
>         for i in range(self.nl):
>             y = self.m[i](x[i])  # conv
>             bs, _, ny, nx = y.shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
>             y = y.view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2)
>             feat.append(y)  # 之前这里只返回了一个 Tensor，其他 Tensor 可能直接释放了
>         return feat 
> 
> 
> 
> detect = Detect(nc=80, anchors=[[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], ch=[128, 256, 512])
> detect.to("cuda")
> 
> x0 = flow.randn(16, 128, 32, 32).to("cuda").requires_grad_()
> x1 = flow.randn(16, 256, 16, 16).to("cuda").requires_grad_()
> x2 = flow.randn(16, 512, 8, 8).to("cuda").requires_grad_()
> x = [x0, x1, x2]
> 
> for i in range(10000):
>     y = detect(x)
>     loss = 0.0
>     for j in range(len(y)):
>         loss += y[j].sum()
>     loss.backward()
>     loss_np = loss.item()
> ```
> 
> 显存占用为 OneFlow: 1360、PyTorch: 1090，batchsize 为 16 的时候差了 270MB 了，可以从这个例子入手去定位。

继续精简发现这个例子即可复现上述问题。

```python
import oneflow as flow
import oneflow.nn as nn

x0 = flow.randn(32, 128, 32, 32).to("cuda").requires_grad_()
x1 = flow.randn(32, 256, 16, 16).to("cuda").requires_grad_()
x2 = flow.randn(32, 512, 8, 8).to("cuda").requires_grad_()
x = [x0, x1, x2]

for i in range(100000000):
    y = x
    loss = 0.0
    for j in range(len(y)):
        loss += y[j].sum()
    loss.backward()
    loss_np = loss.item()
```

显存测试结果：

# bs: 16
# pytorch 841MiB
# oneflow 1247MiB

#bs: 32
# pytorch 873MiB
# oneflow 1281MiB

**Comment by BBuf** [comment]
> 在a100上重新做了实验，发现下述脚本可以复现显存过大的问题：
> 
> ```python
> import oneflow as flow
> import oneflow.nn as nn
> 
> def autopad(k, p=None):  # kernel, padding
>     # Pad to 'same'
>     if p is None:
>         p = k // 2 if isinstance(k, int) else [x // 2 for x in k]  # auto-pad
>     return p
> 
> 
> class Conv(nn.Module):
>     # Standard convolution
>     default_act = nn.SiLU()  # default activation
> 
>     def __init__(self, c1, c2, k=1, s=1, p=None, g=1, act=True):  # ch_in, ch_out, kernel, stride, padding, groups
>         super().__init__()
>         self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p), groups=g, bias=False)
>         self.bn = nn.BatchNorm2d(c2)
>         self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()
> 
> 
>     def forward(self, x):
>         return self.act(self.bn(self.conv(x)))
> 
> 
> class Bottleneck(nn.Module):
>     # Standard bottleneck
>     def __init__(self, c1, c2, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, shortcut, groups, expansion
>         super().__init__()
>         c_ = int(c2 * e)  # hidden channels
>         self.cv1 = Conv(c1, c_, 1, 1)
>         self.cv2 = Conv(c_, c2, 3, 1, g=g)
>         self.add = shortcut and c1 == c2
> 
>     def forward(self, x):
>         return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
> 
> 
> 
> class C3(nn.Module):
>     # CSP Bottleneck with 3 convolutions
>     def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
>         super().__init__()
>         c_ = int(c2 * e)  # hidden channels
>         self.cv1 = Conv(c1, c_, 1, 1)
>         self.cv2 = Conv(c1, c_, 1, 1)
>         self.cv3 = Conv(2 * c_, c2, 1)  # optional act=FReLU(c2)
>         self.m = nn.Sequential(*(Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)))
> 
>     def forward(self, x):
>         return self.cv3(flow.cat((self.m(self.cv1(x)), self.cv2(x)), 1))
> 
> if __name__ == '__main__':
>     model = C3(512, 512, n=9)
>     model.to("cuda")
>     x = flow.randn(16, 512, 40, 40).to("cuda").requires_grad_()
>     for i in range(2000000):
>         y = model(x)
>         loss = y.sum()
>         loss.backward()
>         loss_item = loss.item()
> ```
> 
> oneflow显存占用：3773MiB pytorch显存占用：2645MiB

如果只跑前向，并且使用no_grad把for loop包一下：

pytorch: 1067MiB
oneflow: 2117MiB

可以看到显存也差了一个多G，感觉和autograd应该无关

**Comment by wyg1997** [comment]
我在 2080 上做测试的话，显存差距会小很多：

前后向：

OneFlow：3405MiB
PyTorch：3063MiB

前向：

OneFlow：1563MiB
PyTorch：1351MiB

非常接近 ctx 的占用了，我试试在特殊的 docker 里做实验，把 context 的误差先排除

**Comment by BBuf** [comment]
> 我在 2080 上做测试的话，显存差距会小很多：
> 
> 前后向：
> 
> OneFlow：3405MiB PyTorch：3063MiB
> 
> 前向：
> 
> OneFlow：1563MiB PyTorch：1351MiB
> 
> 非常接近 ctx 的占用了，我试试在特殊的 docker 里做实验，把 context 的误差先排除

是的，在3080ti也不存在这个问题，在a100机器会有这个问题，比较奇怪。

**Comment by BBuf** [comment]
可以确定上述问题是由于cuda context的影响带来的，所以并不存在显存占用比pytorch多很多的问题，本问题关闭。
