### ISSUE TITLE
C++版本的API

### ISSUE THREAD

**Issue by xifen523** [Oneflow-Inc/one-yolov5#90]
将会开发C++版本的调用嘛？能不能实现更快速度的c++呀

**Comment by ccssu** [comment]
> 将会开发C++版本的调用嘛？能不能实现更快速度的c++呀

感谢您咨询。
这里将尝试回答 `将会开发C++版本的调用嘛？这个问题。`

`首先OneFlow是通过C++开发的机器学习框架。`
one-yolov5 是以OneFlow后端，换句话说 one-yolov5 已经是的调用的 `C++` 的 `API接口`。关于速度，我们在单卡上凭借对YOLOv5的性能分析以及几个简单的优化将3090 Ti FP32 YOLOv5s的训练速度提升了近20%。对于需要迭代300个Epoch的COCO数据集来说相比 ultralytics/yolov5 我们缩短了`11.35`个小时的训练时间。我们还将继续提高性能。
优化相关的技术细节可以查看 [消费级显卡的春天，GTX 3090 YOLOv5s单卡完整训练COCO数据集缩短11.35个小时](https://start.oneflow.org/oneflow-yolo-doc/tutorials/00_chapter/optim_speed_version1.html) 这篇文章。

最后，欢迎添加 bbuf23333 进入 One-YOLOv5 微信交流群一起交流 。

**Comment by xifen523** [comment]
我现在想知道  我如果想用oneflow框架 部署这个yolov5 c++版本 怎么实现呢？

**Comment by BBuf** [comment]
> 

部署的话和 ultralytics/yolov5 没有什么区别，都是导出onnx然后使用推理框架比如onnxruntime，tensorrt的，本项目的主要目的是训练加速以及全面解析yolov5帮助大家更清晰的认识本算法。
